apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: <your-worker-image>
          env:
            - name: AWS_ACCESS_KEY_ID
              value: minio
            - name: AWS_SECRET_ACCESS_KEY
              value: minio123
            - name: S3_BUCKET_NAME
              value: transcode
            - name: AWS_S3_ENDPOINT_URL
              value: http://minio:9000
            - name: GST_DEBUG
              value: "1"
            - name: POSTGRES_USER
              value: transcoder
            - name: POSTGRES_PASSWORD
              value: OW14F15rBHRLivihLral
            - name: POSTGRES_DB
              value: transcoding_jobs
            - name: POSTGRES_HOST
              value: postgres
