from distributed_transcoder_common.models import Preset


async def seed_presets():
    presets = [
        {
            "name": "Scale to 1080p x265 (1.5 mbit) mp4->mp4",
            "pipeline": "filesrc location={{input_file}} ! qtdemux name=d mp4mux name=mux ! filesink location={{output_file}} d.audio_0 ! queue max-size-buffers=0 max-size-bytes=0 max-size-time=0 ! decodebin ! audioconvert ! avenc_aac ! mux.audio_0 d.video_0 ! queue max-size-buffers=0 max-size-bytes=0 max-size-time=0 ! decodebin ! videoscale ! video/x-raw,width=1920, height=1080 ! x265enc bitrate=1536 ! {{progress}} ! h265parse ! mux.video_0",
            "input_type": "mp4",
            "output_type": "mp4",
            "video_encoding": "h265",
            "resolution": "1920x1080",
            "video_bitrate": "1536",
            "audio_encoding": "aac",
            "audio_bitrate": "128",
        },
        {
            "name": "Scale to 720p x265 (1 mbit) mp4->mp4",
            "pipeline": "filesrc location={{input_file}} ! qtdemux name=d mp4mux name=mux ! filesink location={{output_file}} d.audio_0 ! queue max-size-buffers=0 max-size-bytes=0 max-size-time=0 ! decodebin ! audioconvert ! avenc_aac ! mux.audio_0 d.video_0 ! queue max-size-buffers=0 max-size-bytes=0 max-size-time=0 ! decodebin ! videoscale ! video/x-raw,width=1280, height=720 ! x265enc bitrate=1024 ! {{progress}} ! h265parse ! mux.video_0",
            "input_type": "mp4",
            "output_type": "mp4",
            "video_encoding": "h265",
            "resolution": "1280x720",
            "video_bitrate": "1024",
            "audio_encoding": "aac",
            "audio_bitrate": "128",
        },
        {
            "name": "Scale to 720p x264 (1 mbit) mp4->mp4",
            "pipeline": "filesrc location={{input_file}} ! qtdemux name=d mp4mux name=mux ! filesink location={{output_file}} d.audio_0 ! queue max-size-buffers=0 max-size-bytes=0 max-size-time=0 ! decodebin ! audioconvert ! avenc_aac ! mux.audio_0 d.video_0 ! queue max-size-buffers=0 max-size-bytes=0 max-size-time=0 ! decodebin ! videoscale ! video/x-raw,width=1280, height=720 ! x264enc bitrate=1536 ! {{progress}} ! h264parse ! mux.video_0",
            "input_type": "mp4",
            "output_type": "mp4",
            "video_encoding": "h264",
            "resolution": "1280x720",
            "video_bitrate": "1024",
            "audio_encoding": "aac",
            "audio_bitrate": "128",
        },
        {
            "name": "Scale to 480p x265 (768 kbit) mp4->mp4",
            "input_type": "mp4",
            "output_type": "mp4",
            "video_encoding": "h265",
            "resolution": "640x480",
            "video_bitrate": "768",
            "audio_encoding": "aac",
            "audio_bitrate": "128",
            "pipeline": "filesrc location={{input_file}} ! qtdemux name=d mp4mux name=mux ! filesink location={{output_file}} d.audio_0 ! queue max-size-buffers=0 max-size-bytes=0 max-size-time=0 ! decodebin ! audioconvert ! avenc_aac ! mux.audio_0 d.video_0 ! queue max-size-buffers=0 max-size-bytes=0 max-size-time=0 ! decodebin ! videoscale ! video/x-raw,width=640, height=480 ! x265enc bitrate=768 ! {{progress}} ! h265parse ! mux.video_0",
        },
        {
            "name": "Scale to 1080p x265 (1.5 mbit) mp4->mkv",
            "pipeline": "filesrc location={{input_file}} ! qtdemux name=d matroskamux name=mux ! filesink location={{output_file}} d.audio_0 ! queue max-size-buffers=0 max-size-bytes=0 max-size-time=0 ! decodebin ! audioconvert ! avenc_aac ! mux.audio_0 d.video_0 ! queue max-size-buffers=0 max-size-bytes=0 max-size-time=0 ! decodebin ! videoscale ! video/x-raw,width=1920, height=1080 ! x265enc bitrate=1536 ! {{progress}} ! h265parse ! mux.video_0",
            "input_type": "mp4",
            "output_type": "mkv",
            "video_encoding": "h265",
            "resolution": "1920x1080",
            "video_bitrate": "1536",
            "audio_encoding": "aac",
            "audio_bitrate": "128",
        },
        {
            "name": "Scale to 720p x265 (1 mbit) mp4->mkv",
            "pipeline": "filesrc location={{input_file}} ! qtdemux name=d matroskamux name=mux ! filesink location={{output_file}} d.audio_0 ! queue max-size-buffers=0 max-size-bytes=0 max-size-time=0 ! decodebin ! audioconvert ! avenc_aac ! mux.audio_0 d.video_0 ! queue max-size-buffers=0 max-size-bytes=0 max-size-time=0 ! decodebin ! videoscale ! video/x-raw,width=1280, height=720 ! x265enc bitrate=1024 ! {{progress}} ! h265parse ! mux.video_0",
            "input_type": "mp4",
            "output_type": "mkv",
            "video_encoding": "h265",
            "resolution": "1280x720",
            "video_bitrate": "1024",
            "audio_encoding": "aac",
            "audio_bitrate": "128",
        },
        {
            "name": "Scale to 480p x265 (768 kbit) mp4->mkv",
            "pipeline": "filesrc location={{input_file}} ! qtdemux name=d matroskamux name=mux ! filesink location={{output_file}} d.audio_0 ! queue max-size-buffers=0 max-size-bytes=0 max-size-time=0 ! decodebin ! audioconvert ! avenc_aac ! mux.audio_0 d.video_0 ! queue max-size-buffers=0 max-size-bytes=0 max-size-time=0 ! decodebin ! videoscale ! video/x-raw,width=640, height=480 ! x265enc bitrate=768 ! {{progress}} ! h265parse ! mux.video_0",
            "input_type": "mp4",
            "output_type": "mkv",
            "video_encoding": "h265",
            "resolution": "640x480",
            "video_bitrate": "768",
            "audio_encoding": "aac",
            "audio_bitrate": "128",
        },
        {
            "name": "Scale to 1080p x265 (1.5 mbit) mkv->mp4",
            "pipeline": "filesrc location={{input_file}} ! matroskademux name=d mp4mux name=mux ! filesink location={{output_file}} d.audio_0 ! queue max-size-buffers=0 max-size-bytes=0 max-size-time=0 ! decodebin ! audioconvert ! avenc_aac ! mux.audio_0 d.video_0 ! queue max-size-buffers=0 max-size-bytes=0 max-size-time=0 ! decodebin ! videoscale ! video/x-raw,width=1920, height=1080 ! x265enc bitrate=1536 ! {{progress}} ! h265parse ! mux.video_0",
            "input_type": "mkv",
            "output_type": "mp4",
            "video_encoding": "h265",
            "resolution": "1920x1080",
            "video_bitrate": "1536",
            "audio_encoding": "aac",
            "audio_bitrate": "128",
        },
        {
            "name": "Scale to 720p x265 (1 mbit) mkv->mp4",
            "pipeline": "filesrc location={{input_file}} ! matroskademux name=d mp4mux name=mux ! filesink location={{output_file}} d.audio_0 ! queue max-size-buffers=0 max-size-bytes=0 max-size-time=0 ! decodebin ! audioconvert ! avenc_aac ! mux.audio_0 d.video_0 ! queue max-size-buffers=0 max-size-bytes=0 max-size-time=0 ! decodebin ! videoscale ! video/x-raw,width=1280, height=720 ! x265enc bitrate=1024 ! {{progress}} ! h265parse ! mux.video_0",
            "input_type": "mkv",
            "output_type": "mp4",
            "video_encoding": "h265",
            "resolution": "1280x720",
            "video_bitrate": "1024",
            "audio_encoding": "aac",
            "audio_bitrate": "128",
        },
        {
            "name": "Scale to 720p x264 (2 mbit) mkv->mp4",
            "pipeline": "filesrc location={{input_file}} ! matroskademux name=d mp4mux name=mux ! filesink location={{output_file}} d.audio_0 ! queue max-size-buffers=0 max-size-bytes=0 max-size-time=0 ! decodebin ! audioconvert ! avenc_aac ! mux.audio_0 d.video_0 ! queue max-size-buffers=0 max-size-bytes=0 max-size-time=0 ! decodebin ! videoscale ! video/x-raw,width=1280, height=720 ! x264enc bitrate=2048 ! {{progress}} ! h264parse ! mux.video_0",
            "input_type": "mkv",
            "output_type": "mp4",
            "video_encoding": "h264",
            "resolution": "1280x720",
            "video_bitrate": "2048",
            "audio_encoding": "aac",
            "audio_bitrate": "128",
        },
        {
            "name": "Scale to 480p x265 (768 kbit) mkv->mp4",
            "pipeline": "filesrc location={{input_file}} ! matroskademux name=d mp4mux name=mux ! filesink location={{output_file}} d.audio_0 ! queue max-size-buffers=0 max-size-bytes=0 max-size-time=0 ! decodebin ! audioconvert ! avenc_aac ! mux.audio_0 d.video_0 ! queue max-size-buffers=0 max-size-bytes=0 max-size-time=0 ! decodebin ! videoscale ! video/x-raw,width=640, height=480 ! x265enc bitrate=768 ! {{progress}} ! h265parse ! mux.video_0",
            "input_type": "mkv",
            "output_type": "mp4",
            "video_encoding": "h265",
            "resolution": "640x480",
            "video_bitrate": "768",
            "audio_encoding": "aac",
            "audio_bitrate": "128",
        },
        {
            "name": "Scale to 1080p x265 (1.5 mbit) mkv->mkv",
            "pipeline": "filesrc location={{input_file}} ! matroskademux name=d matroskamux name=mux ! filesink location={{output_file}} d.audio_0 ! queue max-size-buffers=0 max-size-bytes=0 max-size-time=0 ! decodebin ! audioconvert ! avenc_aac ! mux.audio_0 d.video_0 ! queue max-size-buffers=0 max-size-bytes=0 max-size-time=0 ! decodebin ! videoscale ! video/x-raw,width=1920, height=1080 ! x265enc bitrate=1536 ! {{progress}} ! h265parse ! mux.video_0",
            "input_type": "mkv",
            "output_type": "mkv",
            "video_encoding": "h265",
            "resolution": "1920x1080",
            "video_bitrate": "1536",
            "audio_encoding": "aac",
            "audio_bitrate": "128",
        },
        {
            "name": "Scale to 720p x265 (1 mbit) mkv->mkv",
            "pipeline": "filesrc location={{input_file}} ! matroskademux name=d matroskamux name=mux ! filesink location={{output_file}} d.audio_0 ! queue max-size-buffers=0 max-size-bytes=0 max-size-time=0 ! decodebin ! audioconvert ! avenc_aac ! mux.audio_0 d.video_0 ! queue max-size-buffers=0 max-size-bytes=0 max-size-time=0 ! decodebin ! videoscale ! video/x-raw,width=1280, height=720 ! x265enc bitrate=1024 ! {{progress}} ! h265parse ! mux.video_0",
            "input_type": "mkv",
            "output_type": "mkv",
            "video_encoding": "h265",
            "resolution": "1280x720",
            "video_bitrate": "1024",
            "audio_encoding": "aac",
            "audio_bitrate": "128",
        },
        {
            "name": "Scale to 480p x265 (768 kbit) mkv->mkv",
            "pipeline": "filesrc location={{input_file}} ! matroskademux name=d matroskamux name=mux ! filesink location={{output_file}} d.audio_0 ! queue max-size-buffers=0 max-size-bytes=0 max-size-time=0 ! decodebin ! audioconvert ! avenc_aac ! mux.audio_0 d.video_0 ! queue max-size-buffers=0 max-size-bytes=0 max-size-time=0 ! decodebin ! videoscale ! video/x-raw,width=640, height=480 ! x265enc bitrate=768 ! {{progress}} ! h265parse ! mux.video_0",
            "input_type": "mkv",
            "output_type": "mkv",
            "video_encoding": "h265",
            "resolution": "640x480",
            "video_bitrate": "768",
            "audio_encoding": "aac",
            "audio_bitrate": "128",
        },
    ]

    for preset in presets:
        existing_preset = await Preset.get_or_none(name=preset["name"])
        if not existing_preset:
            await Preset.create(**preset)
